### ISSUE TITLE
Scope separator should be '+'

### ISSUE THREAD

**Issue by rtheunissen** [thephpleague/oauth2-instagram#1]
I think the Instagram scope separator should be `+`. See [docs](https://instagram.com/developer/authentication/#scope)

**Comment by stevenmaguire** [comment]
@rtheunissen I've been following the issue in the main library. With the current functionality of the main library, this is not an issue that requires a code fix in this package as much as it is a documentation fix. 

I've amended the documentation for this package to provide more clarity around how to define multiple, correctly formatted, scopes. Additionally, I have created a test that ensures the authorization url contains properly formatted scopes when following the suggested utilization.

Please review https://github.com/thephpleague/oauth2-instagram#managing-scopes

**Comment by stevenmaguire** [comment]
Reopening. I was mistaken about the scope separator. I'll get another patch out.
