### ISSUE TITLE
Error : Invalid state

### ISSUE THREAD

**Issue by abada** [thephpleague/oauth2-instagram#10]
Can change https://github.com/thephpleague/oauth2-instagram/blob/master/src/Provider/Instagram.php#L40 to `https://instagram.com/oauth/authorize` 

According this comment http://stackoverflow.com/a/41270938/1597574 ?

**Comment by stevenmaguire** [comment]
The latest version should give you the ability to change the host to be any value you desire without breaking any existing consumers' code: https://github.com/thephpleague/oauth2-instagram/releases/tag/0.2.3

You can set the host via instantiation config or after the client has been created. 

```php
$provider = new League\OAuth2\Client\Provider\Instagram([
    'clientId'          => '{instagram-client-id}',
    'clientSecret'      => '{instagram-client-secret}',
    'redirectUri'       => 'https://example.com/callback-url',
    'host'              => 'https://instagram.com' // Optional, defaults to https://api.instagram.com
]);
```

or 

```php
$provider->setHost('https://instagram.com');
```
