### ISSUE TITLE
Comments scope unrecognized

### ISSUE THREAD

**Issue by ctrlaltdylan** [thephpleague/oauth2-instagram#5]
Using the comments, likes, and basic scope during authorization like outlined in the docs (with an array in the $options). But receiving an error from Instagram saying I haven't asked for comment's scope on this particular account. Tried using a string, and also have reauthenticated several times with no luck.

**Comment by waltervos** [comment]
Hi Dylan, unfortunately Instagram requires apps that wish to make POST and DELETE requests (comments, relationships, likes, etc) to specifically ask for access: https://help.instagram.com/contact/185819881608116

This is probably in reaction to all the automated like/comment/follow spam.

**Comment by ctrlaltdylan** [comment]
Ah you know what. Our production app is using the Instagram credentials authorized to comment. My local app is using a test Instagram app I created. That's probably it. Let me test that theory and hopefully I can close out this little issue.

Thanks!

**Comment by waltervos** [comment]
@ctrlaltdylan Any luck?

**Comment by stevenmaguire** [comment]
@waltervos is dead on here. Instagram has changed their policy here and this response is expected now.
