### ISSUE TITLE
Scrutinizer inspections being canceled?

### ISSUE THREAD

**Issue by ramsey** [thephpleague/oauth2-instagram#7]
Why are the Scrutinizer inspections being canceled for this repo? See here:

https://scrutinizer-ci.com/g/thephpleague/oauth2-instagram/inspections

Most of them show an empty log, while the [latest inspection](https://scrutinizer-ci.com/g/thephpleague/oauth2-instagram/inspections/ff614871-0578-4773-8d64-c17ef0066e17) says "Scrutinizer was notified that the tests failed," even though the [build passed on Travis CI](https://travis-ci.org/thephpleague/oauth2-instagram/builds/90211557).

**Comment by waltervos** [comment]
I know, weird. Same thing happened for my pull request: https://github.com/thephpleague/oauth2-instagram/pull/4

**Comment by stevenmaguire** [comment]
I've made some changes to the scrut and travis configs that will correct this. Long story short, travis should only report stable php builds to scrut. Scrut should only expect to receive analysis from stable php builds.
